In [29]:
import pandas as pd

In [30]:
fname='1.csv'

In [31]:
data=pd.read_csv(fname, delimiter=':', header=None, names=('var', 'task', 'res'))
data.head()

         var  task   res
0  Variant 1     1    -2
1  Variant 1     2  BAAC
2  Variant 1     3   768
3  Variant 1     4    64
4  Variant 1     5   166

In [32]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 920 entries, 0 to 919
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   var     920 non-null    object
 1   task    920 non-null    int64
 2   res     920 non-null    object
dtypes: int64(1), object(2)
memory usage: 21.7+ KB

In [33]:
data['var']=data['var'].str.replace('Variant ','').astype(int)

In [34]:
data.tail()

     var  task                  res
915  115     4                   46
916  115     5               syntax
917  115     6  undefined behaviour
918  115     7              BA~A~B=
919  115     8                   -8

In [35]:
keys= data.pivot(columns='task', index='var', values='res')

In [36]:
keys.to_csv('2.csv')